name: karwaservices
description: "The Official Mobile App of Karwa Services"
publish_to: "none"

# The version number is used to identify different versions.
version: 1.0.0+1

environment:
  sdk: ^3.10.3

# Depedencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management Package
  flutter_bloc: ^9.1.1

  provider: ^6.1.5+1 # Temporary state management solution

  #Firebase Packages
  firebase_core: ^4.2.1 # Where all Firebase tools are dependent
  firebase_auth: ^6.1.2 # Package for handling user accounts
  cloud_firestore: ^6.1.0 # For apps connection to the firestore database, allowing the app to read and write data
  firebase_ui_auth: ^3.0.1 # Pre-built UI for Firebase Authentication

  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
