// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFx2kJ7ZeGxFZXePJ--gvjsyNGjSM1q8E',
    appId: '1:76690484332:web:216a0d03754a93ae9fbc49',
    messagingSenderId: '76690484332',
    projectId: 'karwaservices',
    authDomain: 'karwaservices.firebaseapp.com',
    storageBucket: 'karwaservices.firebasestorage.app',
    measurementId: 'G-L6ZH72MHR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBakudUrSJ9owDBxNcM3R5PTvZ-4xCBIPA',
    appId: '1:76690484332:android:77adc0b0a46a11709fbc49',
    messagingSenderId: '76690484332',
    projectId: 'karwaservices',
    storageBucket: 'karwaservices.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw_O6-weXh9nE55JHo7Pk8OfPltfakGr4',
    appId: '1:76690484332:ios:8c9ace59376d73d79fbc49',
    messagingSenderId: '76690484332',
    projectId: 'karwaservices',
    storageBucket: 'karwaservices.firebasestorage.app',
    iosBundleId: 'com.example.ios',
  );
}
